name: "Publish Artifacts to AWS"
author: "Keren Dong"
description: "Publish GitHub artifacts to AWS S3"
inputs:
  artifacts-path:
    description: "Where to find the artifacts"
    required: true
  aws-proxy:
    description: "AWS proxy in /etc/hosts"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
