name: "Publish Prebuilt"
author: "Keren Dong"
description: "Publish Prebuilt to AWS S3"
inputs:
  aws-proxy:
    description: "AWS proxy in /etc/hosts"
  artifacts-path:
    description: "Where to find the artifacts"
  bucket-staging:
    description: "S3 Bucket used as staging area of prebuilt binaries"
  bucket-production:
    description: "S3 Bucket used as production area of prebuilt binaries"
runs:
  using: "node12"
  main: "dist/index.js"
