name: "Publish Prebuilt"
author: "Keren Dong"
description: "Publish Prebuilt to AWS S3"
inputs:
  artifacts-path:
    description: "Where to find the artifacts"
    required: true
  aws-proxy:
    description: "AWS proxy in /etc/hosts"
    required: false
  bucket-prebuilt:
    description: "S3 Bucket for prebuilt binaries"
    default: "kungfu-prebuilt"
    required: false
  bucket-app:
    description: "S3 Bucket for prebuilt app"
    default: "kungfu-app"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
